### ISSUE TITLE
Error: Cannot find module 'webpack'

### ISSUE THREAD

**Issue by peteruithoven** [tomkis1/flux-boilerplate#3]
I'm having issues running the `npm install` script. I ran:

```
git clone git@github.com:tomkis1/flux-boilerplate.git
cd flux-boilerplate
npm install
```

Then doing the post install step it gives the following error

```
> flux-boilerplate@0.1.0 postinstall /Applications/AMPPS/www/flux/reducers/flux-boilerplate
> webpack --config=webpack/webpack.staging.config.js


module.js:340
    throw err;
          ^
Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Applications/AMPPS/www/flux/reducers/flux-boilerplate/webpack/webpack.staging.config.js:2:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

```

I tried installing webpack globally but that doesn't help. 

Running the command seperatly gives the same error

```
$ webpack --config=webpack/webpack.staging.config.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Applications/AMPPS/www/flux/reducers/flux-boilerplate/webpack/webpack.staging.config.js:2:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by peteruithoven** [comment]
Looks like the dev dependencies weren't installed. 
I think I understand why, and it's my fault. Dev dependencies are installed by default unless you use the `--production` flag or set `NODE_ENV` to production. My `NODE_ENV` was set to production.
